---
- hosts: Client
  become: true
  pre-task:
    - name: Update et Upgrade
      apt:
        update_cache: yes
        upgrade: dist

    - name: install pre-requis
      apt:
        name:
          - curl
          - git
          - wget

  tasks:
    - name: Installation Python 3 and pip
      apt:
        name:
        - python3
        - python3-pip
        state: latest

    - name: Installation de Nmap
      apt:
        name: nmap
        state: latest

    - name: Clone Git project SEMABOX
      git:
        repo: https://github.com/user/project.git
        dest: /
        version: master
    
    - name: Check si requirement.txt existe
      stat:
        path: /Semabox/install/requirement.txt
      register: requirement_file

    - name: Fail if requirement.txt does not exist
      fail:
        msg: "requirement.txt does not exist"
      when: not requirement_file.stat.exists

    - name: Installation des dépendances Pythons
      pip:
        requirements: /Semabox/install/requirement.txt

    - name : Copie du Service Semabox-API
      copy:
        src: /Semabox/install/Semabox-api.service
        dest: /etc/systemd/system    

    - name: Première installation de Semabox
      command: python3 /Semabox/install/install.py

    - name: Activation du service Semabox-api
      ansible.builtin.systemd:
        name: Semabox-api.service
        enabled: yes
        state: started


