version: '1.0'
services:
    semabox:
        container_name: semabox
        image: foufoudu34/semabox:latest
        restart: always
        ports:
            - '80:80'
            - '22:22'
        networks:
            - semabox

networks:
    semabox:
    # Changer macvlan par bridge si vous êtes sur Windows ou Mac OS car macvlan n'est pas supporté
    # Pour Windows, il faut aussi changer le driver_opts: parent: eth0 par parent: Ethernet
    # Pour Mac OS, il faut aussi changer le driver_opts: parent: eth0 par parent: en0
        driver: macvlan
        driver_opts:
            parent: eth0
        ipam:
            config:
                - subnet:
                     # Changer les valeurs par celle de votre réseau pour que le container soit dans le même réseau que votre machine
                    # Si vous êtes sur Windows ou Mac OS, mettez se que vous voulez, le container cominuquera avec votre machine via le port 80 mais il ne sera pas dans le même réseau
                    gateway: <votregateway>
                    ip_range: <votrevlan>
                    aux_addresses: <votrevlan>