# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: TEST SEMABOX

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  test-build:
    runs-on: python:3.11.1
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build -t semabox:latest .
    - name: Test Docker image
      run: docker run -dit -h semabox --name semabox -p 22:22 -p 80:80 -d semabox:latest
    - name: Test de connexion au container
      run: docker exec -it semabox bash
